### ISSUE TITLE
Adjust neighborhoods

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/api-food-asset-map#55]
In making the static maps (#41), I noticed that some neighborhoods they told us to focus on don't match what we have in our data. I emailed to clarify:

> I assume SOMA is the same as South of Market? 
You list Richmond. I see both Inner Richmond and Outer Richmond in the data I have. Is it one of those? Both? 
Is Sunset the same as Sunset/Parkside? 

Here's the response I got: 

> Yes, SOMA is South of Market. 
Let's lump together inner and outer Richmond
Sunset (I believe) is distinct from Parkside. But there are an inner and outer Sunset, and that is what we would like displayed (if possible) 

Can we incorporate this into the data we're using, Katie? I'm actually not sure if it's possible given that the data comes at the neighborhood level as the City of SF defines neighborhoods, but please let me know.

**Comment by katiejolly** [comment]
So, the issue is that we wanted neighborhood boundaries that respected census tract boundaries. I interpolated the census tracts to another neighborhood shapefile that is more detailed (it has almost 3 times as many neighborhoods included, rather than having groupings). This would be a good alternative.

![image](https://user-images.githubusercontent.com/21339677/118757663-62bec380-b822-11eb-8c20-da2d4814ed67.png)
![image](https://user-images.githubusercontent.com/21339677/118757695-710cdf80-b822-11eb-9128-fbcfd8867406.png)

**Comment by dgkeyes** [comment]
So if we used the more detailed shapefile can we then aggregate at the level of the neighborhoods as they define them and calculate the % of API population?

**Comment by katiejolly** [comment]
Yep! If you render the index.Rmd I pushed last night you’ll see the results of that. That’s also the image I posted.

**Comment by dgkeyes** [comment]
Ok, thanks! In looking at it, though, I'm still a bit confused. I still see Inner and Outer Richmond (the client wants these lumped into just Richmond). Is this something we can combine? Can you also please rename South of Market to SOMA? Thanks!

**Comment by katiejolly** [comment]
Ah yes right, I forgot about combining those. And yep, the rename is easy.
I'll get this done today!

**Comment by dgkeyes** [comment]
Thanks! When that shapefile is ready, will you please let me know? I need to use it to generate static maps in #41.

**Comment by katiejolly** [comment]
Edited polygon (with Richmond combined and SOMA renamed) is saved as data/api_neighborhood_interpolated.rds

**Comment by dgkeyes** [comment]
Awesome! Everything looks just about right. I went to make the static maps and realized that they have a neighborhood Bayview Hunters Point while our data has Bayview and Hunters Point as separate neighborhoods. I copied your code to try to do this, but I'm getting this error:

> Error in CPL_geos_op2(op, x, y) : 
  Evaluation error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 547234.09534280142 4178620.6091703386 at 547234.09534280142 4178620.6091703386.
In addition: Warning message:
In st_interpolate_aw.sf(race_ethnicity_clean_sf %>% select(-geoid,  :
  st_interpolate_aw assumes attributes are constant or uniform over areas of x

Can you help me here, @katiejolly?

**Comment by katiejolly** [comment]
I’ll take a look mid-morning today!

**Comment by dgkeyes** [comment]
Gracias!

**Comment by katiejolly** [comment]
Who knows why but it works for me! 
![image](https://user-images.githubusercontent.com/21339677/119027324-0b703e80-b95b-11eb-86c0-c30e58e44dab.png)
![image](https://user-images.githubusercontent.com/21339677/119027552-525e3400-b95b-11eb-8787-9c968085e1da.png)

I'll push my changes, but let me know if I'm misinterpreting the issue

**Comment by dgkeyes** [comment]
Ok, it works now for me too. Weird!
